[workspace]
members = [
    "core",
    "net",
    "cli",
    "node",
    "services/storage",
    "services/auth",
    "services/user",
    "services/common",
    "crates/*",

    #"chain/node",
    #"chain/frame/*",
    #"chain/runtime",
]
